"use client";

import { useState } from "react";
import {
  Panel,
  Group as PanelGroup,
  Separator as PanelResizeHandle,
} from "react-resizable-panels";
import { ChatPanel } from "@/components/vibe/chat-panel";
import { PreviewPanel } from "@/components/vibe/preview-panel";
import type { ChatMessage, GeneratedFile } from "@/lib/vibe/types";

const initialMessages: ChatMessage[] = [
  {
    id: "intro-1",
    role: "assistant",
    content:
      "作りたい UI をそのまま書いてください。送信すると Gemini がコードを生成し、E2B sandbox 上で動かして右側に実プレビューを出します。",
  },
];

const promptSuggestions = [
  "和モダンな採用ページ。会社の価値観、社員の声、応募 CTA。",
  "重厚感のあるプロダクト紹介ページ。濃い色、比較表、FAQ。",
  "スタートアップの分析ダッシュボード。KPI、チャート風カード、アクティビティ一覧。",
];

export function V0Workbench() {
  const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
  const [input, setInput] = useState(promptSuggestions[0]);
  const [files, setFiles] = useState<GeneratedFile[]>([]);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [projectTitle, setProjectTitle] = useState("Waiting for your first build");
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSaveToApps = async () => {
    const response = await fetch("/api/apps/save-vibe", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        files,
        name: projectTitle,
        description: `Generated by Vibe Builder: ${projectTitle}`,
        category: "Vibe",
        icon: "✨",
        color: "from-violet-500 to-indigo-500",
      }),
    });
    const data = await response.json();
    if (!response.ok || !data.success) {
      throw new Error(data.message ?? "Failed to save app.");
    }
  };

  const handleSubmit = async () => {
    const trimmed = input.trim();

    if (!trimmed || isLoading) {
      return;
    }

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content: trimmed,
    };

    const nextHistory = [...messages, userMessage];

    setMessages(nextHistory);
    setInput("");
    setError(null);
    setIsLoading(true);

    try {
      const response = await fetch("/api/vibe/build", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          currentFiles: files,
          history: nextHistory,
        }),
      });

      const payload = (await response.json()) as
        | {
          assistantMessage: string;
          files: GeneratedFile[];
          previewUrl: string;
          projectTitle: string;
          sandboxId: string;
        }
        | { error: string };

      if ("error" in payload) {
        throw new Error(payload.error);
      }

      if (!response.ok) {
        throw new Error("Failed to build preview.");
      }

      setFiles(payload.files);
      setPreviewUrl(payload.previewUrl);
      setProjectTitle(payload.projectTitle);
      setMessages((current) => [
        ...current,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: payload.assistantMessage,
        },
      ]);
    } catch (requestError) {
      const message =
        requestError instanceof Error
          ? requestError.message
          : "Failed to build preview.";

      setError(message);
      setMessages((current) => [
        ...current,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          content: `ビルドに失敗しました: ${message}`,
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="shell">
      <div className="shell__backdrop" />
      <header className="topbar">
        <div>
          <p className="eyebrow">Safe Vibe Builder</p>
          <h1>AI chat on the left, live app preview on the right.</h1>
        </div>
        <div className="topbar__badge">
          <span className="status-dot" />
          Gemini + E2B
        </div>
      </header>

      <section className="workspace">
        <PanelGroup orientation="horizontal">
          <Panel defaultSize={38} minSize={28}>
            <ChatPanel
              input={input}
              isLoading={isLoading}
              messages={messages}
              onInputChange={setInput}
              onSubmit={handleSubmit}
              suggestions={promptSuggestions}
            />
          </Panel>

          <PanelResizeHandle className="resize-handle" />

          <Panel defaultSize={62} minSize={36}>
            <PreviewPanel
              error={error}
              files={files}
              isLoading={isLoading}
              previewUrl={previewUrl}
              projectTitle={projectTitle}
              onSaveToApps={files.length > 0 ? handleSaveToApps : undefined}
            />
          </Panel>
        </PanelGroup>
      </section>
    </main>
  );
}
